path: weights/model_trt_fp16.ts
threshold: 0.5
class_names: [
    "agriculture","artisinal_mine", "bare_ground","blooming",
    "blow_down","clear", "cloudy","conventional_mine", 
    "cultivation","habitation", "haze","partly_cloudy", 
    "primary","road", "selective_logging","slash_burn", "water"
]
device: cpu